# Generated by Django 4.0.2 on 2022-02-05 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_input', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
