# Generated by Django 4.0.2 on 2022-02-05 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_input', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(1)])),
                ('steps_date', models.DateField(verbose_name='daily steps')),
            ],
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
