# Generated by Django 4.0.2 on 2022-02-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_question_delete_calendar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
