# Generated by Django 4.0.2 on 2022-02-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0006_calendar_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendar',
            new_name='DailySteps',
        ),
    ]
