# Generated by Django 4.0.2 on 2022-02-10 11:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0007_rename_calendar_dailysteps'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='dailysteps',
            name='steps_date',
            field=models.DateField(unique=True, validators=[django.core.validators.MaxValueValidator(datetime.date.today, message='The date cannot be in the future')]),
        ),
    ]
