# Generated by Django 4.0.2 on 2022-02-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0008_daterange_alter_dailysteps_steps_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateRange',
        ),
    ]
